name: Bug Report
description: Submit a bug report
title: "[Bug Report] Bug title"
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code example
      description: |
        Provide an example code or a stack trace.
        This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: system-info
    attributes:
      label: System info
      description: |
        Describe the characteristic of your environment:
        * What OS/version you're using.
        * Python version


  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: >
            I have checked that there is no similar [issue](https://github.com/tobirohrer/python-project-template/issues)
            in the repo.
          required: true
