name: Question
description: Ask a question
title: "[Question] Question title"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: >
        Do you have any questions related to this project?
        
  - type: textarea
    id: question
    attributes:
      label: Question
      description: Your question
    validations:
      required: true
