name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: pip install .[tests,docs]
    
    - name: Run Tests with pytest
      run: make test
